kind: Service
apiVersion: v1
metadata:
  name: cloudsql
spec:
  type: ClusterIP
  selector:
    name: cloudsql
  ports:
  - name: cloudsql
    port: 5432
    targetPort: cloudsql

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudsql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cloudsql
    spec:
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=$(INSTANCE_CONNECTION_NAME)=tcp:0.0.0.0:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        ports:
        - name: cloudsql
          containerPort: 5432
        env:
        - name: INSTANCE_CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-instance-credentials
              key: instance_connection_name
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        - name: ssl-certs
          mountPath: /etc/ssl/certs
        - name: cloudsql
          mountPath: /cloudsql
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
          items:
          - key: credentials.json
            path: credentials.json
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: cloudsql
        emptyDir: