kind: Service
apiVersion: v1
metadata:
  name: mstdn-cloudsql
spec:
  type: ClusterIP
  selector:
    name: mstdn-cloudsql
  ports:
  - name: mstdn-cloudsql
    port: 5432
    targetPort: mstdn-cloudsql

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mstdn-cloudsql
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: mstdn-cloudsql
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mstdn-cloudsql
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=$(INSTANCE_CONNECTION_NAME)=tcp:0.0.0.0:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        ports:
        - name: mstdn-cloudsql
          containerPort: 5432
        env:
        - name: INSTANCE_CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              name: mastodon-cloudsql-secrets
              key: instance_connection_name
        volumeMounts:
        - name: cloudsql-secrets
          mountPath: /secrets/cloudsql
          readOnly: true
        - name: ssl-certs
          mountPath: /etc/ssl/certs
        - name: cloudsql
          mountPath: /cloudsql
        resources:
          requests:
            memory: 32Mi
            cpu: 25m
      volumes:
      - name: cloudsql-secrets
        secret:
          secretName: mastodon-cloudsql-secrets
          items:
          - key: credentials.json
            path: credentials.json
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: cloudsql
        emptyDir:
