kind: Service
apiVersion: v1
metadata:
  name: mastodon
spec:
  ports:
  - name: web
    port: 3000
    targetPort: web
  - name: streaming
    port: 4000
    targetPort: streaming
  selector:
    name: mastodon

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mastodon
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: mastodon
    spec:
      containers:
      - name: web
        image: tootsuite/mastodon:v2.6.1
        command: ["/bin/ash", "-c", "rails assets:precompile && bundle exec rails s -p 3000 -b 0.0.0.0"]
        ports:
        - name: web
          containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 1
        envFrom:
        - configMapRef:
            name: mastodon-config
        - secretRef:
            name: mastodon-secrets
        resources:
          requests:
            memory: 350Mi
            cpu: 100m
      - name: streaming
        image: tootsuite/mastodon:v2.6.1
        command: ["yarn", "start"]
        ports:
        - name: streaming
          containerPort: 4000
        envFrom:
        - configMapRef:
            name: mastodon-config
        - secretRef:
            name: mastodon-secrets
        resources:
          requests:
            memory: 32Mi
            cpu: 25m

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sidekiq
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: sidekiq
    spec:
      containers:
      - name: sidekiq
        command: ["/bin/ash", "-c", "echo \"${CAFILE_RB}\" > config/initializers/cafile.rb && bundle exec sidekiq -q default -q mailers -q pull -q push"]
        image: tootsuite/mastodon:v2.6.1
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
        env:
        - name: CAFILE_RB
          value: |
            Rails.application.configure do
              config.action_mailer.smtp_settings[:ca_file] = "/etc/ssl/certs/ca-certificates.crt"
            end
        envFrom:
        - configMapRef:
            name: mastodon-config
        - secretRef:
            name: mastodon-secrets
