apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-volume

---

kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    targetPort: redis
  selector:
    name: redis